[theme]
primaryColor = "#E50914"
backgroundColor = "#111418"
secondaryBackgroundColor = "#181D24"
textColor = "#E2E8F0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
